/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 5.0 */
public interface CalculatorTreeConstants
{
  public int JJTPROCEDURENODE = 0;
  public int JJTSTATEMENTNODE = 1;
  public int JJTEXPRESSIONNODE = 2;
  public int JJTADDNODE = 3;
  public int JJTMINUSNODE = 4;
  public int JJTTERMNODE = 5;
  public int JJTTIMESNODE = 6;
  public int JJTDIVIDENODE = 7;
  public int JJTFACTORNODE = 8;


  public String[] jjtNodeName = {
    "ProcedureNode",
    "StatementNode",
    "ExpressionNode",
    "AddNode",
    "MinusNode",
    "TermNode",
    "TimesNode",
    "DivideNode",
    "FactorNode",
  };
}
/* JavaCC - OriginalChecksum=ae24d0ce76c70a8c0a6b19293724cb20 (do not edit this line) */
