/* Generated By:JJTree: Do not edit this line. DivideNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class DivideNode extends SimpleNode {
  public DivideNode(int id) {
    super(id);
  }

  public DivideNode(Calculator p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2ccaaf20f431d91d888dcf6895f68b54 (do not edit this line) */
