/* Generated By:JJTree: Do not edit this line. ExpressionNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ExpressionNode extends SimpleNode {
  public ExpressionNode(int id) {
    super(id);
  }

  public ExpressionNode(Calculator p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b3ebc2bf224e7d4e5446034365fe7b5a (do not edit this line) */
