/* Generated By:JJTree: Do not edit this line. FactorNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class FactorNode extends SimpleNode {
  public FactorNode(int id) {
    super(id);
  }

  public FactorNode(Calculator p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ae235874bf4f08b30a7d63403ae5c8bc (do not edit this line) */
