/* Generated By:JJTree: Do not edit this line. StatementNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class StatementNode extends SimpleNode {
  public StatementNode(int id) {
    super(id);
  }

  public StatementNode(Calculator p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7ef9ac173839c75f15989c58d8d78cc7 (do not edit this line) */
