/* Generated By:JJTree: Do not edit this line. AddNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class AddNode extends SimpleNode {
  public AddNode(int id) {
    super(id);
  }

  public AddNode(SansiScript p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4733d857984c8bfd3ccd68c55f37260c (do not edit this line) */
