/* Generated By:JJTree: Do not edit this line. CommandNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class CommandNode extends SimpleNode {

    public CommandNode(int id) {
        super(id);
    }

    public CommandNode(SansiScript p, int id) {
        super(p, id);
    }

}
/* JavaCC - OriginalChecksum=9879f1b869a250e11a1738e9769cbad2 (do not edit this line) */
