/* Generated By:JJTree: Do not edit this line. DivideNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class DivideNode extends SimpleNode {
  public DivideNode(int id) {
    super(id);
  }

  public DivideNode(SansiScript p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ba3c87386cfc8eb30fd942d4db85db16 (do not edit this line) */
