/* Generated By:JJTree: Do not edit this line. ExpressionNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ExpressionNode extends SimpleNode {
  public ExpressionNode(int id) {
    super(id);
  }

  public ExpressionNode(SansiScript p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=508798a7ac41a81ddc03a21614e82611 (do not edit this line) */
