/* Generated By:JJTree: Do not edit this line. FactorNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class FactorNode extends SimpleNode {
  public FactorNode(int id) {
    super(id);
  }

  public FactorNode(SansiScript p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2d5c3c9caeac6c0a411aca9ddb8132af (do not edit this line) */
