/* Generated By:JJTree: Do not edit this line. MinusNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class MinusNode extends SimpleNode {
  public MinusNode(int id) {
    super(id);
  }

  public MinusNode(SansiScript p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4b0686d6250685def180fc62a0b4e99f (do not edit this line) */
