/* Generated By:JJTree: Do not edit this line. PipeNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class PipeNode extends SimpleNode {
  public PipeNode(int id) {
    super(id);
  }

  public PipeNode(SansiScript p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0d1340af3298b9bf4447d21020b54162 (do not edit this line) */
