/* Generated By:JJTree: Do not edit this line. ProcedureNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ProcedureNode extends SimpleNode {
  public ProcedureNode(int id) {
    super(id);
  }

  public ProcedureNode(SansiScript p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2f1ffc22f6efdd8fd7a17e092b472ebc (do not edit this line) */
