/* Generated By:JavaCC: Do not edit this line. SansiScriptTreeConstants.java Version 5.0 */
public interface SansiScriptTreeConstants
{
  public int JJTPROCEDURENODE = 0;
  public int JJTSTATEMENTNODE = 1;
  public int JJTPIPENODE = 2;
  public int JJTEXPRESSIONNODE = 3;
  public int JJTADDNODE = 4;
  public int JJTMINUSNODE = 5;
  public int JJTTERMNODE = 6;
  public int JJTTIMESNODE = 7;
  public int JJTDIVIDENODE = 8;
  public int JJTFACTORNODE = 9;
  public int JJTCOMMANDNODE = 10;


  public String[] jjtNodeName = {
    "ProcedureNode",
    "StatementNode",
    "PipeNode",
    "ExpressionNode",
    "AddNode",
    "MinusNode",
    "TermNode",
    "TimesNode",
    "DivideNode",
    "FactorNode",
    "CommandNode",
  };
}
/* JavaCC - OriginalChecksum=4584606a96433290627b684534ad1a5e (do not edit this line) */
