/* Generated By:JJTree: Do not edit this line. TermNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class TermNode extends SimpleNode {
  public TermNode(int id) {
    super(id);
  }

  public TermNode(SansiScript p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c087e7c194ff76aeeeb258b027d6b4a4 (do not edit this line) */
