package com.dianping.sansi.interpreter.interpreter.calculator;

/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 5.0 */
public interface CalculatorTreeConstants
{
  public int JJTPROCEDURE = 0;
  public int JJTSTATEMENT = 1;
  public int JJTEXPRESSION = 2;
  public int JJTTERM = 3;
  public int JJTFACTOR = 4;


  public String[] jjtNodeName = {
    "procedure",
    "statement",
    "expression",
    "term",
    "factor",
  };
}
/* JavaCC - OriginalChecksum=efbc9ebd53986e0548dbf2b1ba67c7db (do not edit this line) */
