/* Generated By:JJTree: Do not edit this line. AddNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class AddNode extends SimpleNode {
  public AddNode(int id) {
    super(id);
  }

  public AddNode(Calculator p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0b348d839e8f5abc4cf3223227a82f27 (do not edit this line) */
