/* Generated By:JJTree: Do not edit this line. MinusNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class MinusNode extends SimpleNode {
  public MinusNode(int id) {
    super(id);
  }

  public MinusNode(Calculator p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d166b04657a6c29336fb67d0a2567475 (do not edit this line) */
