/* Generated By:JJTree: Do not edit this line. ProcedureNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ProcedureNode extends SimpleNode {
  public ProcedureNode(int id) {
    super(id);
  }

  public ProcedureNode(Calculator p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4fc11aebaf85b117332132b7ab3920a7 (do not edit this line) */
