/* Generated By:JJTree: Do not edit this line. TermNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class TermNode extends SimpleNode {
  public TermNode(int id) {
    super(id);
  }

  public TermNode(Calculator p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4469a5a17bc6d4a4805d092f19bd7d8d (do not edit this line) */
