/* Generated By:JJTree: Do not edit this line. TimesNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class TimesNode extends SimpleNode {
  public TimesNode(int id) {
    super(id);
  }

  public TimesNode(Calculator p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=81ed820d5411b22035a32123066c69fc (do not edit this line) */
